### ISSUE TITLE
bug on world_data.py?

### ISSUE THREAD

**Issue by paus-5** [coronafighter/coronaSEIR#4]
I get the following error

Traceback (most recent call last):
  File "c:/Users/Pablo/Documents/coronaSEIR/main_coronaSEIR.py", line 8, in <module>
    import population
  File "c:\Users\Pablo\Documents\coronaSEIR\population.py", line 26, in <module>
    countries, provinces = world_data.get_countries_provinces()
  File "c:\Users\Pablo\Documents\coronaSEIR\world_data.py", line 116, in get_countries_provinces
    countries, provinces = get_country_xcdr(returnLists=True)
  File "c:\Users\Pablo\Documents\coronaSEIR\world_data.py", line 60, in get_country_xcdr
    recovered = int(d['recovered']['locations'][i]['history'][date])
IndexError: list index out of range

Is it just me? Any clues why? It worked for me until Monday.

Thanks for the tool btw

**Comment by malawadd** [comment]
i have a similar error

**Comment by hector-chg-data** [comment]
Same error

**Comment by coronafighter** [comment]
Somehow the data changed and does not show recovered any more for some countries. I am just setting this to 0 for now so that it is obvious something is missing in charts.
